### ISSUE TITLE
Mockups for front end prototype

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#1]

**Comment by dmlyons2** [comment]
If the mockups look good - move to done. Else comment why, move back to inprogress or TODO @kdionisio

**Comment by kdionisio** [comment]
Access mock-ups here:

https://usepa.mybalsamiq.com/projects/hem/grid

**Comment by kdionisio** [comment]
Minor comments were added within Balsamiq about the following mock-ups (listed below). Otherwise mock-ups look great!

Population Generator - products
Population Generator - population
Population Generator - region
Population Generator - Review
Population Generator - Results 01

**Comment by dmlyons2** [comment]
Got it - moving to done.
