### ISSUE TITLE
add link to Dashboard

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#107]
Link to that chemical's page in CompTox Dashboard from chemical results page, using DTXSID to search the Dashboard

**Comment by dmlyons2** [comment]
https://comptox.epa.gov/dashboard/
with the dtxsid at the end

**Comment by kdionisio** [comment]
can we have this link go directly to the 'Exposure' tab for that chemical in the Dashboard, rather than landing on the main page for that chemical?

**Comment by dmlyons2** [comment]
Yes, but that would be another issue. This issue has been completed as requested, so I am going to close it out.
