### ISSUE TITLE
fix dose calculation before plotting

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#111]
When entering by chemical, dose to plot is currently calculated by: 
total daily systemic dose = dir_derm_abs + dir_inhal_abs + dir_ingest_abs

Above is incorrect. Should be:

total daily systemic dose = dir_derm_abs + dir_inhal_abs + dir_ingest_abs + ind_derm_abs + ind_inhal_abs + ind_ingest+abs

All other parts of the dose calculation should remain the same. Let me know if you'd like me to come down to make this change, I'm happy to.

**Comment by dmlyons2** [comment]
Completed - but there are side effects that appear to be data related that cause several chemicals not to plot because of negative numbers in the plot.

**Comment by kdionisio** [comment]
Do you have an example of a data record or query that does this and I'll look into it?

**Comment by dmlyons2** [comment]
Moving this to [issue #120](https://github.com/quanted/hem_app/issues/120)

**Comment by dmlyons2** [comment]
@kdionisio - opened a new issue [#120](https://github.com/quanted/hem_app/issues/120) to track this and have added some documentation there. You will see the the numbers are really off - continue conversation on #120.
