### ISSUE TITLE
change product model - add PUCID+SHEDSID

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#114]
In the hem_app_product model, please add 2 columns:
pucid - 17 characters of free text
shedsid - 12 characters of free text

This will help with tracking identifiers for products and associating model runs with products since currently the HEM model operates using shedsid (in the future will be change to operate using pucid)

**Comment by dmlyons2** [comment]
@kdionisio - Is there always a pucid and shedsid or will these values sometimes be blank?

**Comment by kdionisio** [comment]
They could be blank.
