### ISSUE TITLE
Not all Chemicals plotting

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#120]
This is residue from #111  
After adding in the extra ind_derm_abs, ind_inhal_abs, ind_ingest_abs to the get_chemical_data function in the analysis_funcs.py file several of the single chemicals stopped displaying.  This appears to be due to data sets that include negative numbers which do not plot on the log scale and break highcharts.

To see the dataset, right click on the web page and choose "view page source" and near the bottom of the page you will see the dataset used to attempt to build the highcharts chart.  

Here is an example of the chart data from Sodium dodecyl sulfate (151-21-3)

```Javascript
series: [{
                name: '151-21-3',
                color: 'rgba(119, 152, 191, .5)',
                data: [[-44705.696950087251, 0.10724034836864678], [-43173.218749913896, 0.10724034836864678], [-41640.740549740556, 0.10724034836864678], [-40108.262349567201, 0.10724034836864678], [-38575.784149393861, 0.10724034836864678], [-37043.305949220507, 0.10724034836864678], [-35510.827749047166, 0.10724034836864678], [-33978.349548873812, 0.10724034836864678], [-32445.871348700468, 0.10724034836864678], [-30913.393148527121, 0.10724034836864678], [-29380.914948353773, 0.10724034836864678], [-27848.436748180426, 0.10724034836864678], [-26315.958548007078, 0.10724034836864678], [-24783.480347833731, 0.10724034836864678], [-23251.002147660383, 0.68568828805407533], [-21718.523947487036, 0.68568828805407533], [-20186.045747313688, 0.68568828805407533], [-18653.567547140341, 0.68568828805407533], [-17121.089346966994, 0.68568828805407533], [-15588.611146793646, 0.68568828805407533], [-14056.132946620299, 0.68568828805407533], [-12523.654746446951, 0.68568828805407533], [-10991.176546273604, 0.68568828805407533], [-9458.6983461002565, 0.68568828805407533], [-7926.220145926909, 0.68568828805407533], [-6393.7419457535616, 0.68568828805407533], [-4861.2637455802142, 0.68568828805407533], [-3328.7855454068667, 0.68568828805407533], [-1796.3073452335193, 0.68568828805407533], [-263.82914506017175, 99.999999999989015]]
            },
```

**Comment by dmlyons2** [comment]
This was a data issues where several of the abs values were negative. Work around is to change all negative values in database to zero

**Comment by kdionisio** [comment]
@dmlyons2 confirmed this is a bug coming out of the model. Programmers to address it. Note that new dose data is loading (afternoon of 6/13) so you may need to do another change of negative values to zero after that latest data set is fully loaded.
