### ISSUE TITLE
mock files for HEM database - ever/never rules

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#14]

**Comment by kdionisio** [comment]
[neverever_rule_mock.xlsx](https://github.com/quanted/hem_app/files/790351/neverever_rule_mock.xlsx)

Mock 'Ever/Never rules' file, data to be stored in HEM database.

Identifiers include PUCID and EvNevID. 

This file can be considered a 'complete' file. We will have updates to the ever/never rules (resulting in a duplication of this table, with the EvNevID = 2 +), however we anticipate updating these rules infrequently.

**Comment by dmlyons2** [comment]
Column names are likely to cause collisions in the future. We should refactor to meaningful names in the future. 😈
