### ISSUE TITLE
populating chemical drop-down menu

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#144]
There appears to be a bug in how the chemical drop-down menu is being populated with the list of chemicals. The drop-down menu should be populated with the list of unique chemicals which appear in the hem_app_dose table, which have runparams_id = 1.

So, populate drop down with list of chemicals resulting from the following query:
```SQL
SELECT DISTINCT chemical_id FROM dev_hem_dave.hem_app_dose WHERE runparams_id=1;
```
It appears the drop-down is currently being populated with the full set of unique chemicals appearing in the dose table, ie
```SQL
SELECT DISTINCT chemical_id FROM dev_hem_dave.hem_app_dose

**Comment by dmlyons2** [comment]
Still deleting chems, but it is working faster with correct chems
