### ISSUE TITLE
HEMISPHERE domain name

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#149]
hemisphere.epa.gov

**Comment by kdionisio** [comment]
Preferred options:
1.	Hemisphere.epa.gov
2.	Chemex.epa.gov
3.	Hem.epa.gov
4.	Hemi.epa.gov

**Comment by dmlyons2** [comment]
Ticket is with EZTech - EPA Incident # INC000002314458

**Comment by dmlyons2** [comment]
hemisphere.epa.gov/index
