### ISSUE TITLE
change link to GitHub repo

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#185]
Need to change link on HEMISPHERE tool to a new GitHub repo, since we have transitioned HEM model code to a different repo.

Need to figure out how best to do this - really we need to link to 3 repos, which together make up the HEM model (HumanExposure/source2dose, HumanExposure/PopulationHousingGenerator, and the HumanExposure/ProductUseScheduler). Open to suggestions on best way to do this. Perhaps link to a read me posted in Git that explains how to run the three modules together get model results?

**Comment by dmlyons2** [comment]
Sent to main human exposure page for now  https://github.com/orgs/HumanExposure/dashboard
