### ISSUE TITLE
color matrix for plotting dose lines

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#186]
Currently color matrix for plotting dose lines is limited to 12-13 colors. This results in an error when trying to plot a product which includes greater than 12/13 chemicals. Please expand color matrix to allow for plotting of at least 23 chemicals at once. Colors do not need to all be unique (ie, can duplicate a color twice when plotting 23 chemicals).

**Comment by dmlyons2** [comment]
Now has 36 colors (12 repeated 3 times)
