### ISSUE TITLE
testing dataset for popgen output. 50,000 would be sufficient.

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#2]

**Comment by kdionisio** [comment]
GitHub is not allowing me to upload such a large file...please tell me how to do so if there is a way to!

Example popgen output for 500,000 people is at:
L:\Lab\HEM\Population Residential Generator\HEM_POP\output\n500000

Only the 'pophouse.csv' file will need to be stored (pop.csv is simply a subset of pophouse.csv).

**Comment by dmlyons2** [comment]
perfect - that works!
