### ISSUE TITLE
mock files for HEM database - product composition

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#20]

**Comment by kdionisio** [comment]
[prodcomp_mock.xlsx](https://github.com/quanted/hem_app/files/782213/prodcomp_mock.xlsx)

Mock product composition file for HEM database. File provides information on the chemical composition for every PUC, i.e., the chemicals and distribution of weight fractions of each chemical, for each PUC.

Identifiers include ProdCompID, PUCID, and DTXRID.

This is an abbreviated file, full file would be on the order of 40,000 rows per 'set' of product composition data. It is possible we woudl work with two sets of product composition data to start (with each set being ~40,000 rows), but overall the 'sets' of product composition data would be updated infrequently.

**Comment by kdionisio** [comment]
@dmlyons2 Can I assume you have not started working on this issue since it is not in ToDo? I have some edits based on a meeting today that will change the file I posted above.

**Comment by dmlyons2** [comment]
You can make that assumption. @kdionisio

**Comment by kdionisio** [comment]
Updated from original version based on comments from meeting on 2/21.

[prodcomp_mockv2.xlsx](https://github.com/quanted/hem_app/files/791286/prodcomp_mockv2.xlsx)

Mock product composition file for HEM database. File provides information on the chemical composition for every PUC, i.e., the chemicals and point estimate of weight fractions of each chemical, for each PUC.

Identifiers include ProdCompID, PUCID, and DTXRID. We have (newly) added in an additional 'FormulationID.' This will be needed for record keeping within the model, but it is unclear (though unlikely) that we would need to link tables within the database based on this FormulationID.

This is an abbreviated file, full file would be on the order of 40,000 rows per 'set' of product composition data. It is possible we would work with two sets of product composition data to start (with each set being ~40,000 rows), but overall the 'sets' of product composition data would be updated infrequently.
