### ISSUE TITLE
Use anaconda to install git

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#31]

**Comment by gbhander** [comment]
Need ZTech support to install Anaconda. 
Created a ticket now.

**Comment by dmlyons2** [comment]
Hi @gbhander - you should not need admin or ez tech to install. If you are still having probs ping me and I will walk over to your office. Dave

**Comment by gbhander** [comment]
@dmlyons2 Hi Dave, I need help to install Git now. Do you have few min tomorrow to install? I am playing with the PyCharm, do you have any codes examples in PyCharm?  Thanks - Raj

**Comment by dmlyons2** [comment]
@gbhander Hi Raj, Have you [tried this link](https://git-scm.com/download/win)? It should start the download automatically. Just like the anaconda install you will just be installing it for yourself, not all users. Let me know if you are still having problems and we can link up on the phone on Thursday (Mar 2).

**Comment by gbhander** [comment]
@dmlyons2 thanks Dave, yes, I have installed and it works now. I will play with it today. I will be off tomorrow. Do you have some time to discuss the next to topics on Monday? I can also help you in database if you need my help.
