### ISSUE TITLE
Git Training

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#32]
If you are not already familiar, take a look at the [git docs](https://git-scm.com/documentation) and/or a tutorial like [Try Git](https://try.github.io/levels/1/challenges/1)

**Comment by gbhander** [comment]
I called eztech and they told me to get the manager’ approval first. I have submitted the approval request.

**Comment by gbhander** [comment]
@dmlyons2 Hi Dave, sorry to bother you, where can I find the project link to connect with the Git? I am getting the following message:
GBhander@LT2626CGBHANDER MINGW64 ~/desktop
$ git clone https://github.com/quanted/hem_app/projects
Cloning into 'projects'...
remote: Not Found
fatal: repository 'https://github.com/quanted/hem_app/projects/' not found
GBhander@LT2626CGBHANDER MINGW64 ~/desktop

**Comment by dmlyons2** [comment]
The project for qed_ hem is https://github.com/quanted/qed_hem.git in that repo you will find a file called dev-setup.txt that explains how to get the project going. 

from dev-setup.txt:
`#clone`
`git clone https://github.com/quanted/qed_hem.git`

`#after cloning a project with submodules`
`#fetch data and checkout appropriate project`
`git submodule update --init --recursive `

`#update hem_app`
`cd hem_app`
`#head will be detached`
`git checkout master`

`#secret key for qed_hem`
`# the file secret_key_django_dropbox.txt is shared` 
`# on dropbox in directory ubertool_keys (or by other means)`
`# needs to be placed the qed_hem directory`

`#pycharm configuration`
`#change interpreter to 2.7.* with django, etc`
`#also edit configuration (qed_hem django button)`
`#add local_settings.py to environmental variables for qed_hem (use + to the right):`
`#DJANGO_SETTINGS_MODULE=settings_local;PYTHONUNBUFFERED=1`

**Comment by dmlyons2** [comment]
Hi @gbhander - please close all the issues that you have in the done column :)
