### ISSUE TITLE
PhysChem Properties file

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#34]
Full first version of file for uploading into database

**Comment by kdionisio** [comment]
@dmlyons2 
Please load the 'hem_app_chemical.csv' file located in the below folder into the 'hem_app_chemical' table
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017

Ticket can be closed once this file is loaded into the database successfully.

**Comment by dmlyons2** [comment]
@kdionisio 
Load complete, there were 4 warnings
+---------+------+----------------------------------------------------------+
| Level   | Code | Message                                                  |
+---------+------+----------------------------------------------------------+
| Warning | 1264 | Out of range value for column 'half_air_hr' at row 5371  |
| Warning | 1264 | Out of range value for column 'half_air_hr' at row 9947  |
| Warning | 1264 | Out of range value for column 'half_air_hr' at row 15453 |
| Warning | 1264 | Out of range value for column 'half_air_hr' at row 18860 |
+---------+------+----------------------------------------------------------+

**Comment by kdionisio** [comment]
Closing this out - though there were minimal errors in loading this file will need to be updated once a correct/complete file is obtained so will worry about errors at that point.
