### ISSUE TITLE
Ever Never rules file

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#35]
Full first version of file for uploading into database

**Comment by kdionisio** [comment]
@dmlyons2 can you load this file into the neverever model/table? It is not a large file but MySql is still freezing up when I try to load it using the import button. The file should be ready to load as-is, let me know if there are problems.
file is here:
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017
the 'hem_app_neverever.csv' for the neverever model

**Comment by dmlyons2** [comment]
@kdionisio => This file 'hem_app_neverever.csv' looks like a chemical file and does not match the neverever model - perhaps I am missing something?
