### ISSUE TITLE
Human Behavior Output file

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#39]
Full first version of file for uploading into HEM database

**Comment by kdionisio** [comment]
@dmlyons2  please load hem_app_behavior_part1.csv located at 
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017
into the behavior table.
**Update I've also put the _part2.csv file in the same folder. If there are not major issues loading then part 2 can be loaded as well. If you find major issues let me know and I'll fix them and resave.

Note this is 1/4 of the behavior table. Please let me know how loading this goes. If there are things I need to change/correct I can do so and re-save so it is ready to load Monday morning. Also let me know how the DB can handle this amt of data  - this is a first glimpse.  It looks like for behavior, for 250 households, we have 12 million rows and 1.25 GB. Can we handle 100 times that (2500 households)? 1000 times that?

**Comment by dmlyons2** [comment]
@kdionisio - multiple errors. Looks like most of them are related to 'NA' in a field - here  is a sample:

 Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 29  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 29  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 29     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 42   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 42  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 42  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 42  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 42     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 43   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 43  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 43  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 43  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 43     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 58   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 58  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 58  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 58  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 58     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 59   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 59  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 59  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 59  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 59     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 85   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 85  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 85  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 85  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 85     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 92   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 92  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 92  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 92  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 92     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 93   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 93  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 93  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 93  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 93     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 94   |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 94  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 94  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 94  |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 94     |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 108  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 108 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 108 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 108 |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 108    |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 109  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 109 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 109 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 109 |
| Warning | 1366 | Incorrect integer value: 'NA' for column 'flag' at row 109    |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_ht' at row 116  |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_iet' at row 116 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_oet' at row 116 |
| Warning | 1366 | Incorrect decimal value: 'NA' for column 'dur_det' at row 116

**Comment by kdionisio** [comment]
@dmlyons2 updated file without NAs is located at L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017

Please load hem_app_behavior_part1.csv into the behavior model. I will continue with saving parts 2-4 unless there are errors with part 1.

**Comment by dmlyons2** [comment]
@kdionisio - took 9mins with no errors. Ready for the rest of the files.

**Comment by dmlyons2** [comment]
@kdionisio All 4 files loaded, no issues.
