### ISSUE TITLE
Dose file

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#40]
First full version of file for uploading into HEM database

**Comment by kdionisio** [comment]
Will need to change data types in 'dose' model for some variables:

intake_derm_mgkgBW_d --> decimal(14, 6)
intake_inhal_mgkgBW_d --> decimal(10,6)
peak_hourly_air_conc_ug_m3 --> decimal(14,6)
peak_dermal_loading_ug --> decimal(10,6)
disposal_solid_waste_ug --> decimal(15,6)
disposal_window_ug --> decimal(14,6)
disposal_sanitary_drain_ug --> decimal(16,6)
disposal_outdoor_surface_ug --> decimal(14,6)

After changing these data types, dose file can be loaded into table. Dose file is called 'hem_app_dose.csv' and is located here:
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017

**Comment by dmlyons2** [comment]
@kdionisio - done!
