### ISSUE TITLE
Product composition file

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#41]
First full version of file to upload into HEM database

**Comment by kdionisio** [comment]
@dmlyons2 Please load the 'hem_app_composition.csv' file located at
 L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017
into the hem_app_composition model

**Note** one thing that needs to be done before loading - within the .csv file the 'chemical_id' is listed as the DTXSID. This DTXSID will need to be mapped over to the integer 'id' in the chemical table. Also note these SID/RID numbers are fudged a bit right now...I'm trying to get with Chris to get this all sorted out.

**Comment by dmlyons2** [comment]
Query used for load:  
  
```SQL 
LOAD DATA LOCAL INFILE '/home/dlyonsl/hem_app_composition.csv'  
INTO TABLE hem_app_composition FIELDS TERMINATED BY ',' ENCLOSED BY '"'   
ignore 1 lines (id, formulation_id, weight_fraction, created_at, updated_at,   
@chemical, product_id, data_type, productcomp_id)  
SET chemical_id = (SELECT id FROM hem_app_chemical WHERE dtxsid = @chemical);
```

**Comment by kdionisio** [comment]
@dmlyons2 As an alternative, I have output a version of the composition file which has the chemical_id included (so would eliminate the step of mapping DTXSID to chemical_id that you have been doing). I know this is not a long term solution but I output this version in case it helps in figuring out why this file isn't loading. File is 'hem_app_composition_Wchemical_id.csv' if you want to try it.  The file DOES have id, created at, and updated at columns, so with the chemical_id in there, it should be able to be loaded as-is.

**Comment by dmlyons2** [comment]
@kdionisio I broke the file into 35 parts and am loading them individually. They are loading without error and each file takes about 45 mins - will discuss speed issues next week.

**Comment by dmlyons2** [comment]
@kdionisio the total count on this table was 3854000. Please take a look at the table and move to done if it looks ok :)

**Comment by kdionisio** [comment]
Done!!
