### ISSUE TITLE
model for PhysChem properties

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#50]

**Comment by dmlyons2** [comment]
@kdionisio referencing the xlxs in [issue 13 ](https://github.com/quanted/hem_app/issues/13) - do we need all of the columns listed? Also would we also want the DTXSID in case there is a change in the future?

**Comment by kdionisio** [comment]
@dmlyons2 Here is an updated example of what actual data variables/columns are needed for the chemical properties table (I checked in with Kristin to get the latest on what is needed/not needed)
[chem_properties.xlsx](https://github.com/quanted/hem_app/files/883367/chem_properties.xlsx)

re. the chemical identifier -let me call you about that if you are free around 3 - I'm on a call now.

**Comment by kdionisio** [comment]
@dmlyons2 in chemical model, please change variable/column name 'dtxrid' to be 'dtxsid' (only if it doesn't cause any trouble...)
This variable actually is the SID not the RID, and I want to be clear with the variable name
