### ISSUE TITLE
model for ever never rules

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#53]

**Comment by kdionisio** [comment]
hold off on model for updated mock file

**Comment by kdionisio** [comment]
@dmlyons2 Here are the variables needed for the ever/never table:
(Note for Kathie, ABM model input file (FullENT.csv)

id
PUCID (defined in same way as you have defined PUCID in all the products table)
(all variables below are binary 0/1)
No2017
HUP
IUP
Seasonality
M
F
W
B
A
N
P
O
age0_5
age6_12
age13_15
age16_18
age19_49
age50plus
kownrent
sewdis
dishwash
stoven
cars
pcprint
swim
yard
Hot_Warm
Cool
Cold

**Comment by kdionisio** [comment]
@dmlyons2 neverever model is missing the 'age19_49' variable (should be tinyint(1))

**Comment by dmlyons2** [comment]
@kdionisio Fixed.
