### ISSUE TITLE
Model for Human Behavior

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#55]

**Comment by kdionisio** [comment]
Need a new mock file before starting to work on this ticket

**Comment by dmlyons2** [comment]
Created to tables:

LongActivity tab is the **behave_activity** table
 - Activity is renamed title
 - RunID is renamed dataset_id  

PersonSpecHabPrac tab is the **behave_person** table

**Comment by kdionisio** [comment]
@dmlyons2  Due to changes in module output we need to change the behave_activity and behave_person models. behave_activity and behave_person can be deleted. Instead new model 'behavior' with the following variables (can change column names as needed)

id
dataset_id
product_id
person_id
person_household_index (integer)
person_diary (integer)
diary_category (text less than 50 characters)
gender (M or F)
age (integer from 0 and 99)
day_of_year (integer from 1-364)
start_time_hr (decimal(6,2))
duration_hr (decimal(6,2))
activity_code (integer from -2 through 7)
dur_ht (decimal(6,2))
dur_iet (decimal(6,2))
dur_oet (decimal(6,2))
dur_det (decimal(6,2))
flag (integer from 1 to 4)

**Comment by dmlyons2** [comment]
@kdionisio Completed, db is updated
