### ISSUE TITLE
model for habits and practices

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#59]

**Comment by kdionisio** [comment]
hold off on model for updated mock file

**Comment by kdionisio** [comment]
@dmlyons2 Here are the variables need for this table:

(Note to Kathie - from sheds_variables.csv ABM input file)

id
PUCID (defined in same way as you have defined PUCID in other tables/products table)
variable (free text, 25 characters max)
units (free text, 25 characters max)
gender (M, W, B (for men, women, both)....I can recode this however you'd like, perhaps M, F, B for consistency with gender in other tables?)
min.age (integer from 0 to 99)
max.age (integer from 0 to 99)
form (free text, 25 characters max)
mean (number with up to 7 decimal places)
cv (number with up to 7 decimal places)

**Comment by dmlyons2** [comment]
Had to rename some variables   

 puc_id = models.TextField(max_length=120, default='')
    variable_value = models.TextField(max_length=25, default='')
    units = models.TextField(max_length=25, default='')
    gender = models.CharField(max_length=1)
    min_age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(99)])
    max_age = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(99)])
    form_value = models.TextField(max_length=25, default='')
    mean_value = models.DecimalField(decimal_places=7, max_digits=14)
    cv_value = models.DecimalField(decimal_places=7, max_digits=14)
