### ISSUE TITLE
Select a chemical

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#73]
1. The list of chemicals should only be the list of chemicals in the chemical table that have associated products (the unique list of chems in the composition table)
2. They should be selecting on cas

**Comment by dmlyons2** [comment]
```SQL
SELECT DISTINCT chemical_id, hem_app_chemical.cas, hem_app_chemical.title 
FROM hem_app_composition, hem_app_chemical
WHERE chemical_id = hem_app_chemical.id
ORDER BY cas
```

**Comment by kdionisio** [comment]
@dmlyons2  I thought we changed this to be the list of available chemicals for a user to select was the list of unique chemicals present in the DOSE table (not the composition table, as stated above)?
