### ISSUE TITLE
Dose Output File (Chemical)

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#75]
As as user
I would like to download a csv file of the dose used in the model run
so that I can extend the results for my own purposes,

Subset the dose table by person id that is in the person selection (person.csv)
Subset by run_params where category = all
Subset by the chemical selected

from dose table
- person id
- day
- intake_ingest_mgkgBW_d
- intake_derm_mgkgBW_d
- intake_inhal_mgkgBW_d
- peak_hourly_air_conc_ug_m3
- peak_dermal_loading_ug 
- disposal_solid_waste_ug
- disposal_window_ug
- disposal_sanitary_drain_ug
- disposal_outdoor_surface_ug

**Comment by kdionisio** [comment]
Select by chemical – 
Options for chemicals the user can ‘run’ the model for are the unique list of chemicals present in dose table. Currently this is limited to chemicals 1, 2, and 3 (CAS 100-00-5, 100-01-6, 100-02-7). Thus you can only test the 'select by chemical' query using one of these three chemicals. 

The only people present in the dose table are person 1 (1 yr old female), 2 (25 year old male), and 3 (65 year old male). Thus you can only test the select by chemical query using the gender/age combination for one of these people. Alternatively, you can test the query using ‘both’ genders and ‘all’ ages and then you should get results for all 3 of these people in the dose file, for the chemical you chose.

**Comment by kdionisio** [comment]
@dmlyons2 Before working on this query, please load the 'hem_app_dose_temp.csv' file from 
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017
 into the dose table in the DB. AFter this is loaded I can update the runparams table and add a comment here as to what specific parameters can be used to test queries based on data present.

**Comment by dmlyons2** [comment]
Wrong branch on demo :(
