### ISSUE TITLE
People or Population csv 

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#78]
As as user
I would like to download a csv file of the people used in the model run
so that I can extend the results for my own purposes,

Subset the Person table by gender selected, age range selected
columns:
- id
- gender
- race
- ethnicity
- age_years
- ages
- genders
- baths
- lot
- dishwash
- cwasher
- swim

**Comment by kdionisio** [comment]
In terms of testing the above query, note that the person table is currently populated with a FULL data set of 1,000 people. These people cover ages 0-94 yrs (age_years variable) and both genders (M/F; age_gender variable). So any query you would like to run (any age range, any gender) should work.
