### ISSUE TITLE
Dose Output File (Products)

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#79]
As as user
I would like to download a csv file of the doses used in the model run
so that I can extend the results for my own purposes,

Subset the dose table by person id that is in the person selection (person.csv)
Subset by run_params where category = is category picked

from dose table
- person id
- day
- intake_ingest_mgkgBW_d
- intake_derm_mgkgBW_d
- intake_inhal_mgkgBW_d
- peak_hourly_air_conc_ug_m3
- peak_dermal_loading_ug
- disposal_solid_waste_ug
- disposal_window_ug
- disposal_sanitary_drain_ug
- disposal_outdoor_surface_ug

**Comment by kdionisio** [comment]
@dmlyons2 Before working on this query, please load the 'hem_app_dose_temp.csv' file from
L:\Lab\HEM\Web Tool\Avimimus Sprint file for HEM database March 2017
into the dose table in the DB. This file should be loaded in addition to the entries already in the dose table. After this is loaded I can update the runparams table and add a comment here as to what specific parameters can be used to test queries based on data present.

Note the hem_app_dose_temp.csv file does NOT include an 'id' column and does NOT include created at or updated at columns

**Comment by dmlyons2** [comment]
Successfully loaded.
```SQL
LOAD DATA LOCAL INFILE '/home/dlyonsl/hem_app_dose_temp.csv' 
INTO TABLE hem_app_dose 
  FIELDS TERMINATED BY ',' 
  ENCLOSED BY '"' 
  IGNORE 1 LINES 
  (day, intake_ingest_mgkgBW_d, intake_derm_mgkgBW_d, intake_inhal_mgkgBW_d, 
  peak_hourly_air_conc_ug_m3, peak_dermal_loading_ug, disposal_solid_waste_ug,
  disposal_window_ug, disposal_sanitary_drain_ug, disposal_outdoor_surface_ug, 
  chemical_id, person_id, runparams_id) 
SET created_at = NOW(), updated_at = NOW();

**Comment by kdionisio** [comment]
Select by product –
Options for products the user can ‘run’ the model for are the unique list of products OR categories present in hem_app_runparams table, **exempting** category_id=158. Thus currently the user will be able to run the model for product_id=253 OR product_id=275. As such testing of this query can only be done for product_id=253 or product_id=275. 

The only people present in the dose table are person 1 (1 yr old female), 2 (25 year old male), and 3 (65 year old male). Thus you can only test the select by product query using the gender/age combination for one of these people. Alternatively, you can test the query using ‘both’ genders and ‘all’ ages and then you should get results for all 3 of these people in the dose file, for the product_id you chose.
