### ISSUE TITLE
Update dose model in HEM DB

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#84]

**Comment by kdionisio** [comment]
Please update the dose model with the following variables, due to changes in the model output from the S2D model.

@dmlyons2 Note I am a bit worried about the way we are storing data types as I see the numbers coming out of model output. Can we store all true 'data' variables in the dose model as scientific notation with 3-4 significant figures? We could have numbers within the same field where the value varies by orders of magnitude depending on which chemical the result/row corresponds to. I'm wondering if scientific notation is the most efficient way to deal with this? Note that any data currently stored in the dose table is going to be deleted regardless.
**Update 5/25/2017 - Dave the variables I refer to above are the ones we discussed on the phone possibly storing as floats.

Looking at the current dose model, KEEP:
id
day
created_at
updated_at
chemical_id
person_id
runparams_id

All other variables can be deleted. New 'data' variables we need are the following:
dir_derm_exp
dir_derm_max
dir_derm_abs
dir_inhal_exp
dir_inhal_mass
dir_inhal_max
dir_inhal_abs
dir_ingest_exp
dir_ingest_abs
release
ind_derm_exp
ind_derm_max
ind_derm_abs
ind_inhal_exp
ind_inhal_max
ind_inhal_mass
ind_inhal_abs
ind_ingest_exp
ind_ingest_abs
out_sur
out_air
drain
waste

**Comment by dmlyons2** [comment]
@kdionisio - this changes the dose download. Which fields do you want in the dose file now?

**Comment by kdionisio** [comment]
@dmlyons2 All of the 'data' fields listed above should be included in the dose download file
