### ISSUE TITLE
LCIA metrics download file on output page

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#96]

**Comment by kdionisio** [comment]
1. Note that the LCIA metrics download file is ONLY applicable when a user searches by PRODUCT CATEGORY. If the user searches by chemical, there will be no LCIA metrics file.

2. When a user searches by product category, query will find run_params id number that corresponds to the product category of interest

3. Within the hem_app_lifecycleimpact table, pull all rows corresponding to the runparams_id identified above

4. File format for download file:
- chemical_id but listed as the CAS not the actual chemical_id number
- all 'data' columns from hem_app_lifecycleimpact table, as is (so mass_frac_chem_puc through mass_tot_land columns

5. Query to test on:
search by product category (for either of the product categories we currently have in the database, ie hand soap or toothpaste), should result in 6 rows in the LCIA download table. Note at this point the same query will result in nothing in the 'dose' download file.

**Comment by kdionisio** [comment]
Doesn't look like this is querying the correct results, is this a result of my fake data or is there a bug in the query?

**Comment by kdionisio** [comment]
This file download is no longer appearing on the output page for 'by product.' Is this a result of data in the database or a bug in coding? It did appear at one point.

Also note that the PL has now decided to NOT include the LCIA metrics file as a download option at this time. So in some ways the bug noted above does not matter, but I want to be sure the download file does not *start* appearing at some point.

**Comment by dmlyons2** [comment]
The development server was updated and there were side effects that I have already fixed but not pushed to development. Since it is completed, I am going to close this issue and you can enter another issue at the end of the sprint to have it removed.
