### ISSUE TITLE
Plot by products

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#99]

**Comment by kdionisio** [comment]
This ticket should be completed after #110 
Also see #111 for correct dose calculation

User should be selecting by product (not by category). When user selects a product, query should pull the dose data for the run number associated with that product
1. user selects product on input page
2. search product_id within hem_app_runparams to find same product_id that user selected
3. find run id associated with the above
4. Plot data from dose table that is associated with the run id from 3, and the appropriate age/gender filters. Note when plotting this data you will plot a separate line for each chemical in this data set.

**Comment by kdionisio** [comment]
Also note the 'shampoo' run is your best test case - shampoo (run 4) has been updated to include a run of 1,000 households, with 4 chemicals in shampoo. Thus when you select shampoo, currently a plot with 4 different chemicals should appear.

Related, we can probably increase the number of bin sizes used in the plotting code at this point since we are now plotting more data. I believe you are currently using number of bins = 10, perhaps play around with bin sizes of 50 or so to see how it changes the curve.

**Comment by kdionisio** [comment]
Update - I have now loaded results for 'surface cleaner spray' (run 5, 1,000 households, 4 chemicals), so you can test this product in addition to shampoo. As with shampoo, there should be 4 chemicals which are plotted when you select surface cleaner spray.

**Comment by dmlyons2** [comment]
The query to make the negative numbers zeros is 
````SQL
update dev_hem_dave.hem_app_dose set ind_ingest_abs = 0 where ind_ingest_abs < 0
````
It can not be run during a load as the table will be locked

**Comment by kdionisio** [comment]
Ran the above query on the ind_ingest_abs, ind_inhal_abs, and ind_derm_abs columns. So all should have only positive numbers. Will run query after loading any additional data until bug in model code is resolved.

**Comment by dmlyons2** [comment]
After running the query you will get some information about how many rows matched the query, how many were changed, and warnings. If warnings is > 0, the next query to run is SHOW WARNINGS; which will give you more details on why it did not work.

**Comment by dmlyons2** [comment]
FYI - when running for product 'surface cleaner' the dose file created is nearly 2GB in size (nearly 700,000 rows) and this is for just two chemicals. It is not an easy filesize to download and takes a loooong time to open in Excel.
